# Problem 2
# https://projecteuler.net/problem=1
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms
# will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

# Libao Jin
# March 15, 2015

def Fibonacci(n):
	s = [1,2]
	c = len(s)
	while True:
		tmp = s[c-1] + s[c-2]
		if tmp <= n:
			s.append(tmp)
			c = len(s)
		else:
			break
	return s

s = Fibonacci(4000000)
t = 0
for i in s:
	if i % 2 == 0:
		t += i
print t
